<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Update person</title>
    
    <style>
		 @media screen and (min-width: 600px) {
          .wrapper {
            display: grid;
            grid-template-columns: 1fr 2fr;
            column-gap: 5%;
          }
		}
    body{
        font-family:tahoma;
        background-color:#eee;

    }
    input[type=submit] {
        font-size:110%;
        background-color:green;
        color:white;
        border-radius: 4px;
    }
    select {
        width: 100%;
        padding: 16px 20px;
        border: none;
        border-radius: 4px;
        background-color: #fff;
        font-size:110%;
        margin:5px 0 5px 0;
        border:1px solid #333;
        }
	
		h3{
		text-align:center;
		color: Blue;
			line-height: 20px;
		}
	
	
	
</style>
</head>
<body>
    <?php
        
        //database connection variables for the database on your web server
        include 'dbconnect.php';

        //we start a try and catch block to attempt to connect to our database and run the query. If it fails, we see the error/exception generated by the catch
        
        try {
            if($_SERVER['REQUEST_METHOD'] == 'GET')
            {
                
              $conn = new PDO("mysql:host=$servername;dbname=$database", $username, $password); //building a new connection object
                // set the PDO error mode to exception
                $conn->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);

                $id = $_GET['id']; //the ID of the person we want to edit from the URL
                
                $sql = $conn->prepare("SELECT * FROM participant WHERE id = ?");
                $sql -> bindValue(1, $id); //we bind this variable to the first ? in the sql statement

                $sql -> execute(); //execute the statement

                $row = $sql->fetch();
                
                //saving all of the data about the person so we can use them later to populate the form fields.              			
				$firstname = $row['firstname'];
				$surname = $row['surname'];
				$email = $row['email'];
				$power_output = $row['power_output'];
				$distance = $row['distance'];
				$club_id = $row['club_id'];
				
				
				
                //using an include to seperate the echo statement that handles the form
                //this allows us to seperate code so it is easier to manage
                include "update_participant_form.php";

                echo '<hr><br>';
                
            }
            else{
                $conn = new PDO("mysql:host=$servername;dbname=$database", $username, $password); //building a new connection object
                // set the PDO error mode to exception
                $conn->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
                
                $id = $_POST['id']; //the ID of the person we wanted to edit from the hidden form field
                
				$firstname = $_POST['firstname'];
				$surname = $_POST['surname'];
				$email = $_POST['email'];
				$power_output = $_POST['power_output'];
				$distance = $_POST['distance'];
				$club_id = $_POST['club_id'];
				
               

                $sql = $conn->prepare("UPDATE participant SET firstname = :firstname, surname = :surname, email = :email, power_output = :power_output, distance = :distance, club_id = :club_id WHERE id = :id");
                $sql -> bindParam(':firstname', $firstname); 
				$sql -> bindParam(':surname', $surname);
				$sql -> bindParam(':email', $email); 
				$sql -> bindParam(':power_output', $power_output);
				$sql -> bindParam(':distance', $distance);
				$sql -> bindParam(':club_id', $club_id); 
				
				$sql -> bindParam(':id', $id); 
               
                
                $sql -> execute(); //execute the statement
				//$sql->debugDumpParams();
				 echo "<a href='admin_menu.php'>Back to Admin portal</a>";
				echo"<br>";
                echo "<h3>Participant updated</h3>";

            }
        }
        catch(PDOException $e)
            {
            echo $e->getMessage(); //If we are not successful in connecting or running the query we will see an error
            }
        ?>

</body>
</html>